language: java
jdk:
- openjdk12

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

script:
- ./gradlew check --info
- ./gradlew linuxX64Test --info
- ./gradlew --project-dir samples assemble

after_success:
- bash <(curl -s https://codecov.io/bash)
- |
  if [[ $TRAVIS_TAG == v* ]]; then
    ./gradlew publish --info -PbintrayPublish=1
  fi
